name: Commands

on: ['push']

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: |
          echo "The current server time is $(date)"
          echo "$(ifconfig)"
      - name: Exporting Var
        run: |
          echo "my_Var=Cali is my Name" >> GITHUB_ENV
          echo "my_Var_2=Sammy is my GF" >> GITHUB_ENV
      - name: From Exporting
        run: |
          echo ${{ env.my_Var}}
          echo ${{env.my_Var_2}}