name: Commands

on: ['push']

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: |
          echo "The current server time is $(date)"
          echo "$(ifconfig)"