name: Commands

on: ['push']

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Exporting Var
        run: |
          echo "my_Var=Cali is my Name" >> $GITHUB_ENV
          echo "my_Var_2=Sammy is my GF" >> $GITHUB_ENV
          echo "my_Var_3=Yahoo mi password" >> $GITHUB_ENV
      - name: From Exporting
        run: |
          echo $my_Var
          echo $my_Var_2
          echo $my_Var_3