name: Conditional If Equal Or 
# since this time is including an or for my repo it will run as opossed to conditonal.yml
on: [push]
jobs:
  hello-world:
    if: github.repository == 'octo-org/octo-repo-prod' || github.repository == 'Cert-Organization/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"