name: Contexts

on: ['push']

jobs:
  my_context:
    runs-on: ubuntu-latest
    steps:
      - name: myAction
        run: echo Hello
        env:
          MY_ACTION: ${{github.action}}
