name: Dependant Jobs Build, Test, and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [packaging, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy application
        run: echo "Deploying to production..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test application
        run: echo "Running tests..."

  build:
    needs: packaging
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build application
        run: echo "Building the application..."

  packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test application
        run: echo "Running tests..."