name: steps

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate number
        id: generate-number
        run: echo "number=$RANDOM" >> $GITHUB_OUTPUT

      - name: Use number
        id: use-number
        run: echo "The number is ${{ steps.generate-number.outputs.number }}"