name: Using ENV global, job and step

on: ['push']

env: 
  globalEnvDay: Monday    
jobs:
  commands:
    runs-on: ubuntu-latest
    env: 
      jobEnvDay: "Tuesday"
    steps:
      - name: Exporting Var
        env: 
          stepEnvDay: "Webnesday"
        run: |
          echo "Firt Day: $globalEnvDay"
          echo "Second Day: $jobEnvDay"
          echo "Firt Day: $stepEnvDay"
